name: move tags

on:
  release:
    types:
      - "created"

jobs:
  tags-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fabasoad/tagger@feat/support-os
        with:
          # The prefix of the semantic tags.
          # Default: ''
          prefix: linux
  tags-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fabasoad/tagger@feat/support-os
        with:
          # The prefix of the semantic tags.
          # Default: ''
          prefix: win
  tags-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fabasoad/tagger@feat/support-os
        with:
          # The prefix of the semantic tags.
          # Default: ''
          prefix: macos
