name: Test VCToolsRedistDir
on:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - run: |
          Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\msvcp140.dll') .
          dir
