name: move tags

on:
  push:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - id: info
        run: |
          bin=$dir\\tagger.exe
          echo $bin
          echo "BIN=$bin" >> $GITHUB_OUTPUT
        env:
          dir: ${{ runner.temp }}
        shell: sh
      - run: |
          echo ${{ steps.info.outputs.BIN }}
        shell: sh
